env:
  DJANGO_VERSION=1.11.26
  DJANGO_VERSION=2.1
  DJANGO_VERSION=2.2
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies

install:
  - pip install pipenv
  - pipenv lock --dev
  - pipenv sync --dev
# command to run tests
script:
  - pytest --testmon project
